registry = "croparia:melons"
path = "botanypots/recipe/${id.namespace}/melon/${id.path}.json"
dependencies = "botanypots"
template = """
{
  "type": "botanypots:crop",
  "seed": {
    "item": "${seed}"
  },
  "categories": [
    "crop", "farmland"
  ],
  "growthTicks": 600,
  "display": {
    "type": "botanypots:aging",
    "block": "${stem}"
  },
  "drops": [
    {
      "chance": 1.00,
      "output": {
        "item": "${melon}"
      }
    },
    {
      "chance": 0.01,
      "output": {
        "item": "${seed}"
      }
    }
  ]
}
"""