registry = "croparia:crops"
path = "croparia/recipe/crafting/material/${id.namespace}/${id.path}.json"
template = """
{
  "type": "minecraft:crafting_shapeless",
  "ingredients": [
    "${fruit}"
  ],
  "result": ${material.result.stack}
}
"""