registry = "croparia:melons"
path = "${melon.namespace}/loot_table/blocks/${melon.path}.json"
template = """
{
  "type": "minecraft:block",
  "pools": [
    {
      "rolls":1,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "${melon}"
        }
      ]
    }
  ]
}
"""