registry = "croparia:melons"
path = "${stem.namespace}/loot_table/blocks/${stem.path}.json"
template = """
{
  "type": "minecraft:block",
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "${seed}"
        }
      ]
    },
    {
      "rolls": 0.01,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "${seed}",
          "conditions": [
            {
              "condition": "minecraft:block_state_property",
              "block": "${stem}",
              "properties": {
                "age": "7"
              }
            }
          ]
        }
      ]
    }
  ]
}
"""