registry = "croparia:melons"
path = "croparia/tags/item/seeds/melons.json"
type = "croparia:aggregated"
startup = true
content = '    "${seed}"'
template = """
{
  "replace": false,
  "values": [
${content}
  ]
}
"""