registry = "croparia:crops"
path = "modern_industrialization/recipe/croparia/packer/${id.namespace}/{id.path}.json"
dependencies = "modern_industrialization"
template = """
{
  "type": "modern_industrialization:packer",
  "duration": 100,
  "eu": 2,
  "item_inputs": [
    {
      "item": "${fruit}",
      "count": 1
    }
  ],
  "item_outputs": [
    {
      "item": "${material.result.id}",
      "count": ${material.result.amount},
      "components": ${material.result.components}
    }
  ]
}
"""