registry = "croparia:melons"
path = "minecraft/tag/block/bee_growables.json"
type = "croparia:aggregated"
startup = true
content = '    "${stem}"'
template = """
{
  "replace": false,
  "values": [
${content}
  ]
}
"""