registry = "croparia:crops"
path = "thermal/recipe/croparia/insolator/${id.namespace}/${id.path}.json"
dependencies = "thermal_expansion"
template = """
{
  "type": "thermal:insolator",
  "ingredient": {
    "item": "${seed}"
  },
  "result": [
    {
      "item": "${seed}",
      "chance": 0.01
    },
    {
      "item": "${fruit}",
      "chance": 1.0
    }
  ],
  "energy_mod": 1.5,
  "water_mod": 1.5,
  "experience": 0.2
}
"""