registry = "croparia:elements"
path = "thermal/recipe/croparia/crystallizer/${name}.json"
dependencies = "thermal_expansion"
template = """
{
  "type": "thermal:crystallizer",
  "ingredients": [
    {
      "fluid": "${fluid_source}",
      "amount": 250
    },
    {
      "item": "${gem}"
    }
  ],
  "result": [
    {
      "item": "${gem}",
      "amount": 2
    }
  ]
}
"""