registry = "croparia:melons"
path = "thermal/recipe/croparia/insolator_melon/${id.namespace}/${id.path}.json"
dependencies = "thermal_expansion"
template = """
{
  "type": "thermal:insolator",
  "ingredient": {
    "item": "${seed}"
  },
  "result": [
    {
      "item": "${seed}",
      "chance": 0.01
    },
    {
      "item": "${melon}",
      "chance": 1.0
    }
  ],
  "energy_mod": 1.5,
  "water_mod": 1.5,
  "experience": 0.2
}
"""