registry = "croparia:melons"
path = "${id.namespace}/blockstates/${stem.path}.json"
startup = true
template = """
{
  "variants": {
    "age=0": {
      "model": "croparia:block/stem_stage0"
    },
    "age=1": {
      "model": "croparia:block/stem_stage1"
    },
    "age=2": {
      "model": "croparia:block/stem_stage2"
    },
    "age=3": {
      "model": "croparia:block/stem_stage3"
    },
    "age=4": {
      "model": "croparia:block/stem_stage4"
    },
    "age=5": {
      "model": "croparia:block/stem_stage5"
    },
    "age=6": {
      "model": "croparia:block/stem_stage6"
    },
    "age=7": {
      "model": "croparia:block/stem_stage7"
    }
  }
}
"""