modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/MUYUTwilighter/croparia-if/issues"
license = "MIT with Additional Terms"

[[mods]]
modId = "croparia"
version = "${version}"
displayName = "Croparia-If"
authors = "MUYU_Twilighter, xwjcool, Dalarion"
description = '''
Farm minerals, loots and even more!
'''
logoFile = "icon.png"

[[dependencies.croparia]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.croparia]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.croparia]]
modId = "architectury"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.croparia]]
modId = "jei"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.croparia]]
modId = "rei"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.croparia]]
modId = "emi"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "croparia-if-common.mixins.json"

[[mixins]]
config = "croparia-if-neoforge.mixins.json"